# Github Actions workflow file for the gateway
name: Gateway

on:
    push:
        branches:
            - dev
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote SSH commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/
                      echo "🔄 Cтягиваем код с github"
                      echo "🗑 Очищаем следы прошлых запусков, если имеются"
                      if [ -d "streaming-communication" ]; then
                          rm -rf streaming-communication
                      fi
                      git clone git@github.com:VladyslavDobrovolskyi/streaming-communication.git
                      cd streaming-communication
                      git checkout dev
                      git pull
                      rm -rf .git

                      echo "🔄 Остановка и пересборка контейнера"
                      echo "🛑 Проверка наличия контейнера streaming-communication"
                      if [ $(docker ps -q -f name=streaming-communication) ]; then
                          echo "🛑 Остановка контейнера streaming-communication"
                          docker stop streaming-communication || true
                          docker rm streaming-communication || true
                      fi

                      echo "🗑 Удаление предыдущего образа streaming-communication, если он существует"
                      if [ $(docker images -q streaming-communication) ]; then
                          docker rmi streaming-communication || true
                      fi

                      echo "🛠 Пересборка контейнера streaming-communication без кэша"
                      docker build -t streaming-communication .

                      echo "🔍 Проверка наличия сети streaming-network"
                      if [ ! $(docker network ls -q -f name=streaming-network) ]; then
                          echo "🌐 Сеть streaming-network не найдена, создаем сеть"
                          docker network create streaming-network
                      fi

                      echo "🚀 Запуск контейнера streaming-communication"
                      docker run -d --name streaming-communication \
                        --network streaming-network \
                        -p 9999:9999 \
                        streaming-communication

                      echo "🔍 Проверка, что контейнер streaming-communication поднялся"
                      if [ $(docker ps -q -f name=streaming-communication) ]; then
                          echo "✅ Контейнер streaming-communication успешно запущен"
                      else
                          echo "❌ Контейнер streaming-communication не запущен"
                          exit 1
                      fi
                      cd /home/ubuntu/

                      echo "🗑 Очищаем пространство"
                      if [ -d "streaming-communication" ]; then
                          rm -rf streaming-communication
                      fi

                      echo "✅ Деплой завершен успешно!"
