# Github Actions workflow file for the gateway
name: Gateway

on:
    push:
        branches:
            - dev
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Executing remote SSH commands using password
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: ${{ secrets.PORT }}
                  script: |
                      cd /home/ubuntu/
                      echo "🔄 Cтягиваем код с github"
                      echo "🗑 Очищаем следы прошлых запусков, если имеются"
                      if [ -d "streaming-gateway" ]; then
                          rm -rf streaming-gateway
                      fi
                      git clone git@github.com:VladyslavDobrovolskyi/streaming-gateway.git
                      cd streaming-gateway
                      git checkout dev
                      git pull
                      rm -rf .git

                      echo "🔄 Остановка и пересборка контейнера"
                      echo "🛑 Проверка наличия контейнера streaming-gateway"
                      if [ $(docker ps -q -f name=streaming-gateway) ]; then
                          echo "🛑 Остановка контейнера streaming-gateway"
                          docker stop streaming-gateway || true
                          docker rm streaming-gateway || true
                      fi

                      echo "🗑 Удаление предыдущего образа streaming-gateway, если он существует"
                      if [ $(docker images -q streaming-gateway) ]; then
                          docker rmi streaming-gateway || true
                      fi

                      echo "🛠 Пересборка контейнера streaming-gateway без кэша"
                      docker build -t streaming-gateway .

                      echo "🔍 Проверка наличия сети streaming-network"
                      if [ ! $(docker network ls -q -f name=streaming-network) ]; then
                          echo "🌐 Сеть streaming-network не найдена, создаем сеть"
                          docker network create streaming-network
                      fi

                      echo "🚀 Запуск контейнера streaming-gateway"
                      docker run -d --name streaming-gateway \
                        --network streaming-network \
                        -p 8888:8888 \
                        --restart always \
                        streaming-gateway

                      echo "🔍 Проверка, что контейнер streaming-gateway поднялся"
                      if [ $(docker ps -q -f name=streaming-gateway) ]; then
                          echo "✅ Контейнер streaming-gateway успешно запущен"
                      else
                          echo "❌ Контейнер streaming-gateway не запущен"
                          exit 1
                      fi
                      cd /home/ubuntu/

                      echo "🗑 Очищаем пространство"
                      if [ -d "streaming-gateway" ]; then
                          rm -rf streaming-gateway
                      fi

                      echo "✅ Деплой завершен успешно!"
